controllers:
  resource:
    path:      ../src/Controller/
    namespace: App\Controller
  type: attribute

#Route
blog_index:
  path:       /blog/{page}
  # значення контролера має формат 'controller_class::method_name'
  controller: App\Controller\BlogController::index
  methods:    GET
  defaults:
    page:  1
    title: "Blog Index"
  requirements:
    #a regular expression that matches a single-digit number of any length
    page: '\d+'

blog_show:
  path:       /blog/{slug}
  # значення контролера має формат 'controller_class::method_name'
  controller: App\Controller\BlogController::show
  methods:    GET
  defaults:
    title: "Blog Show"

lucky_page:
  path:       /lucky/number/{maxInt}
  controller: App\Controller\LuckyController::number
  methods:    GET

redirect_page:
  path:       /redirect
  controller: App\Controller\RedirectController::index
  methods:    GET

blog_service:
  path:       /service
  controller: App\Controller\ServiceController
  methods:    GET

random_message:
  path:       /random
  controller: App\Controller\RandomMessageController
  methods:    GET

download:
  path:       /download
  controller: App\Controller\DownloadController
  methods:    GET


